### ISSUE TITLE
Warnings when loading the TreatmentPatterns package

### ISSUE THREAD

**Issue by ablack3** [darwin-eu-dev/TreatmentPatterns#106]
I'm not totally sure what's causing these messages on the package load but it would be nice to clean this up so there are no warnings when the user loads the package.

```
Restarting R session...

> library(TreatmentPatterns)
Creating a generic function for ‘toJSON’ from package ‘jsonlite’ in package ‘googleVis’
Warning messages:
1: replacing previous import ‘data.table::last’ by ‘dplyr::last’ when loading ‘TreatmentPatterns’ 
2: replacing previous import ‘data.table::first’ by ‘dplyr::first’ when loading ‘TreatmentPatterns’ 
3: replacing previous import ‘data.table::between’ by ‘dplyr::between’ when loading ‘TreatmentPatterns’ 
```

**Comment by mvankessel-EMC** [comment]
I took a look at this, this should be resolved on dev: 6435bcc0f2ea09e2eb96f65b0a48ea796d075f96 and beta: 6435bcc0f2ea09e2eb96f65b0a48ea796d075f96, in an effort to make the package pass R-CMD-check.
