### ISSUE TITLE
Add SD to outputDurationEras

### ISSUE THREAD

**Issue by AniekMarkus** [darwin-eu-dev/TreatmentPatterns#115]
**Is your feature request related to a problem? Please describe.**
Do not only output mean duration, but add standard deviation to indicate variability (this was requested by a reviewer in an earlier study). 

**Describe the solution you'd like**
Add more output to **outputDurationEras** function, e.g.:
- standard deviation
- median
- min/max

This can easily be incorporated in -> 
result <- file[,.(AVG_DURATION=round(mean(duration_era),3), COUNT = .N), by = c("event_cohort_name", "event_seq")][order(event_cohort_name, event_seq)]

**Describe alternatives you've considered**
It's easy to add in the output, but requires rerunning the analysis if not saved, so I would include it so it is available if asked for/necessary when analysing the results.

**Comment by mvankessel-EMC** [comment]
Merged into dev 1ddb859c6c3c74d1c59674f578e2aac5ccb62412
