### ISSUE TITLE
Accounting for loss to follow-up during study period

### ISSUE THREAD

**Issue by edward-burn** [darwin-eu-dev/TreatmentPatterns#128]
In treatmentPatterns, we describe a treatment pathway analysis of a study population of interest. This pathway will necessarily cover some amount of time (which might be years). In our data we have loss to follow up over time as people either leave the database for reasons such as them moving to another area but also because people die. The degree to loss to follow-up will depend on the type of study population (e.g an elderly or particularly sick cohort will likely have a lot of people leaving the cohort as time passes) and also the type of database (e.g. a hospital database may well have much more loss to follow-up than a primary care database).

I´m wondering how, if at all, we can account for this in a treatment patterns at the analysis stage (i.e. not by restricting a cohort to require that they have survived x number of years which may problematic for various research questions)? @mvankessel-EMC @AniekMarkus does the package already allow us to account for loss to follow up in some way (and separate out whether it was due to administrative censoring or death)?

As this was prompted by a couple of current studies which would likely require this functionality, tagging @talita-duarte, @daniprietoalhambra, @daniellenewby

**Comment by daniprietoalhambra** [comment]
I think this is a very important feature we need to add as soon as we can. It is a must that we can report how many people are included at each step of the analysis in an attrition table/flowchart of sorts. Is this in pipeline @mvankessel-EMC ?

**Comment by daniprietoalhambra** [comment]
Failing to account for this is very problematic, e.g. we would be counting deaths as treatment discontinuations because dead people don't usually get treatments :-)

**Comment by mvankessel-EMC** [comment]
>does the package already allow us to account for loss to follow up in some way (and separate out whether it was due to administrative censoring or death)?

Short answer, no.

I do however think this is an important feature, and should be the top priority for TreatmentPatterns, after the after the recent update.



> I think this is a very important feature we need to add as soon as we can. It is a must that we can report how many people are included at each step of the analysis in an attrition table/flowchart of sorts. Is this in pipeline @mvankessel-EMC ?

TreatmentPatterns reports how many people it filters out for each step. I am not entirely sure if this is just logged in the console. If this is the case I will look into a feature that collects that information and stores it in some way.

 

> Failing to account for this is very problematic, e.g. we would be counting deaths as treatment discontinuations because dead people don't usually get treatments :-)

Relying on the death table in the CDM is a logical first step, however it is my understanding that deaths are often not reported. I am not entirely sure how we would be able to determine if people have passed away in any other manner besides the death table.

**Comment by daniprietoalhambra** [comment]
Re death, we do have good data on mortality in most darwin eu databases, so that would make sense

**Comment by mvankessel-EMC** [comment]
I've been working on an implementation to include deceased people for TreatmentPatterns.

## Dummy data
I've used Eunomia for testing data, and injected new records in the death table and the cohort table.

I have generated 500 persons that fit the following criteria:
1. Have Viral Sinusitis (target cohort 7).
2. Treated with Acetaminophen (event cohort 1), 10 days after diagnosis, ends at 100 days.
3. Treated with Aspirin (event cohort 3), 130 days after diagnosis, ends at 210 days.
4. Deceased at 250 days after diagnosis.

Or in Allen Interval Algebra:

TreatmentPattern = Viral Sinusitis di (Acetaminophen < Aspirin < Deceased)

### Generating the dummy data
I've sampled 500 random dates between 1960-01-01 and 2000-01-01
```
cohort_start_date <- sample(seq(
  as.Date("1960-01-01"),
  as.Date("2000-01-01"),
  by = "day"),
  500)
```

I've then used these dates as a basis to set the dates for the target cohort (7) and some treatment cohorts (1, 3).
```
synthPersons <- data.frame(
  cohort_definition_id = c(
    rep(7, length(cohort_start_date)),
    rep(1, length(cohort_start_date)),
    rep(3, length(cohort_start_date))),
  subject_id = c(
    seq(1:length(cohort_start_date)) + 8000,
    seq(1:length(cohort_start_date)) + 8000,
    seq(1:length(cohort_start_date)) + 8000),
  cohort_start_date = c(
    cohort_start_date,
    cohort_start_date + 10,
    cohort_start_date + 130),
  cohort_end_date = c(
    cohort_start_date + 3650*2,
    cohort_start_date + 100,
    cohort_start_date + 210)
  )
```

Finally, I've 'killed' my synthetic persons at 250 days after the cohort_start_date.
```
synthDeath <- data.frame(
  person_id = synthPersons$subject_id,
  death_date = synthPersons$cohort_start_date + 250
)
```

This data is then inserted into the cohort table and the `cdm.death` table.

## TreatmentPatterns
TreatmentPatterns will fetch the death records of the persons defined in the cohort table. Then TreatmentPatterns treats the death event as another event cohort when computing pathways.

If we would then make a Sankey Diagram of that it would look like this:
![image](https://user-images.githubusercontent.com/112690347/228275909-eed43f30-b93c-4e5c-9295-abc36f07bb36.png)

## Follow up
1. Updating query that fetches the death records to be more robust.
2. A non-hacky way to deal with the `minEraDuration`, as the duration of the 'death' cohort is 0 days, and will always be filtered if not dealt with.
3. Maintainer work like updating tests, documentation, etc. to account for the changes, and actually releasing the update.

**Comment by mvankessel-EMC** [comment]
> @mvankessel-EMC one other aspect to this is people who have an observation end date during the study period (because they left the database for a reason other than death). Would it be possible to incorporate this in a similar way?

I think it would be possible. However, I'd like to know 1) your reasoning as to why it would be problematic to include this in the cohort definition, or to include such an event as a event cohort. 2) What data in what tables would you look at? I'm assuming these event can be quite varied between studies.

I'm trying to prevent a one-off solution that works in this case, but is redundant, or not compatible with future studies.

Another way to include deaths, or any other event in a TreatmentPatterns study would be to include them as an event cohort. Out of curiosity, could you rerun your study, that includes high mortality including this [death event cohort](https://atlas-demo.ohdsi.org/#/cohortdefinition/1782298)?

To include deaths, would then not require any alteration to the behavior of the package, and would be transferable to any other exiting event. The only issue I see would be the `minEraDuration` parameter, throwing out events that last less time than defined here. A work around for now would be to set `minEraDuration` to 0, but in future special event cohorts like this should be ignored.

**Comment by edward-burn** [comment]
@mvankessel-EMC so for death I imagine we could indeed treat that as an event cohort and have it generated by the user along with the others (using an Atlas or capr cohort definition). I suppose I was imagining that the death cohort would though have to be treated differently compared to other cohorts (e.g. with some of the pathway settings not making sense for death, like the era duration setting you mention). I suppose the question therefore is whether the package should treat a death cohort as equivalent to any other event cohort? I don't know the code well enough to know, but just looking at the settings the user is asked to provide (minEraDuration, splitEventCohorts, eraCollapseSize, combinationWindow, etc) these don't seem to apply if we're talking about a death cohort as compared to a drug cohort.

For censoring not due to death by this I meant we see a person with a) an obsevation period end date during the study period and b) they did not have a death date on the same day (ie we see they left the database but not because of death). Again I suppose one way could be to specify this as an event type cohort (although probably needing custom sql as I'm not sure you can do it in Atlas), but with the similar problem of whether this equivalent to the typical event cohorts and how this interacts with the various pathway settings.

@mvankessel-EMC what do you think? Maybe this is worth a conversation with @talita-duarte, @daniprietoalhambra, and @daniellenewby to better understand the needs of their studies (which I think would be pretty representative of future studies where censoring is of particular interest to the user)

**Comment by mvankessel-EMC** [comment]
> @mvankessel-EMC so for death I imagine we could indeed treat that as an event cohort and have it generated by the user along with the others (using an Atlas or capr cohort definition). I suppose I was imagining that the death cohort would though have to be treated differently compared to other cohorts (e.g. with some of the pathway settings not making sense for death, like the era duration setting you mention). I suppose the question therefore is whether the package should treat a death cohort as equivalent to any other event cohort? I don't know the code well enough to know, but just looking at the settings the user is asked to provide (minEraDuration, splitEventCohorts, eraCollapseSize, combinationWindow, etc) these don't seem to apply if we're talking about a death cohort as compared to a drug cohort.
> 
> For censoring not due to death by this I meant we see a person with a) an obsevation period end date during the study period and b) they did not have a death date on the same day (ie we see they left the database but not because of death). Again I suppose one way could be to specify this as an event type cohort (although probably needing custom sql as I'm not sure you can do it in Atlas), but with the similar problem of whether this equivalent to the typical event cohorts and how this interacts with the various pathway settings.
> 
> @mvankessel-EMC what do you think? Maybe this is worth a conversation with @talita-duarte, @daniprietoalhambra, and @daniellenewby to better understand the needs of their studies (which I think would be pretty representative of future studies where censoring is of particular interest to the user)

I definitely think its worth to have a conversation with @talita-duarte, @daniprietoalhambra, and @daniellenewby.

If the following implementation would be sufficient for their needs I would heavily favor it, as it is the easiest to implement and the most robust solution for any similar future needs.

_Note that the following is dummy code and not implemented in TreatmentPatterns_

We define our cohort Settings with an extra cohort type, called **exitCohorts**.
```
cohortSettings <- createCohortSettings(
   targetCohorts = data.frame(
     cohortId = c(1),
     cohortName = c("someDisease")),
   eventCohorts = data.frame(
     cohortId = c(2, 3),
     cohortName = c("DrugA", "DrugB")),
   exitCohorts = data.frame(
     cohortId = c(4),
     coohortName = c("Deceased"))
)
```

Resulting in the following data frame of cohorts:
| cohortId | cohortName | cohortType |
| --- | --- | --- |
| 1 | someDisease | target |
| 2 | DrugA | event |
| 3 | DrugB | event |
| 4 | Deceased | exit |

Based on the cohortType the exit cohort(s) could then be ignored during any filtering steps, but then still be included during the construction of the pathways.

**Comment by daniprietoalhambra** [comment]
thoughts on the above proposal @daniellenewby @talita-duarte @edward-burn ? We are gonna need a solution for the upcoming mm study

**Comment by daniellenewby** [comment]
Hey everyone - i think what @mvankessel-EMC has suggested makes sense by having an "exit cohort" for death but also I think the code needs to also pick out if persons left the database too so picking apart those who stopped abit more - was it because they genuinely stopped (which is plausible for anti dem drugs as they are only effective for a certain period of time and have not very nice side effects) or because they died (again likely as older populations) or left the database (which might be small but that is an assumption). Thanks for setting up the meeting it would be great to discuss this further and thanks for all your work on this so far! :)

**Comment by mvankessel-EMC** [comment]
The outcome from the previously mentioned meeting:

1. Implementation of the suggested solution of using ‘exit cohorts’.
2. A default exit cohort will be included for deaths.
3. A re-run of a high mortality study will be done.
4. We can then address any occurring anomalies that are not expected, i.e. treatment after death.

**Comment by daniprietoalhambra** [comment]
[like]  Daniel Prieto Alhambra reacted to your message:
________________________________

**Comment by mvankessel-EMC** [comment]
I've implemented and tested a first iteration of the solution.

![image](https://github.com/darwin-eu-dev/TreatmentPatterns/assets/112690347/943fd49b-a724-4bdf-925f-d73f97b540ac)
With the following TreatmentPattern: Acetaminophen -> Aspirin -> Death

The user interface for the cohort settings remains very similar:
```
cohortSettings <- TreatmentPatterns::createCohortSettings(
  targetCohorts = targetCohort,
  eventCohorts = eventCohorts,
  exitCohorts = exitCohorts
)
```
This is the only change users will notice. By default exitCohorts are set to NULL, which if it is exitCohorts will be completely ignored.

Some follow up issues that I'm looking into.
1. Death only shows up in the SankeyDiagram, but not in the sunburst plot.
2. There is no check for if there are event occurrences after the exit criteria.

**Comment by mvankessel-EMC** [comment]
The sunburst plot now also displays correctly.
![image](https://github.com/darwin-eu-dev/TreatmentPatterns/assets/112690347/a31d0a6f-230d-4dbb-9232-d94e95a8d7b0)

**Comment by edward-burn** [comment]
This seems very nice @mvankessel-EMC , can you please liaise with @daniellenewby to see how well this works for her dementia project (as this should I think be a good example)

**Comment by mvankessel-EMC** [comment]
Closing this, as exit cohorts have been included for a while now.
