### ISSUE TITLE
Update package website

### ISSUE THREAD

**Issue by ablack3** [darwin-eu-dev/TreatmentPatterns#130]
Several examples on the package website are out of date. It looks like the function signatures have changed. This request is for someone to go through the package website and make sure all of the examples work with the current code.

https://darwin-eu-dev.github.io/TreatmentPatterns

For example [launchResultsExplorer](https://darwin-eu-dev.github.io/TreatmentPatterns/reference/launchResultsExplorer.html) is not in the package anymore.

**Comment by mvankessel-EMC** [comment]
I've updated the site, in the associated PR.

**Comment by mvankessel-EMC** [comment]
PR has been merged.
