### ISSUE TITLE
Restrict cohort download to relevant cohorts

### ISSUE THREAD

**Issue by schuemie** [darwin-eu-dev/TreatmentPatterns#134]
Currently the package will download the entire cohort table (see [here](https://github.com/darwin-eu-dev/TreatmentPatterns/blob/main/R/ConstructPathways.R#LL71C12-L71C12)). However, it might be more efficient to restrict to only those cohorts specified in the analysis. This could be achieved by adding a simple `WHERE cohort_definition_id IN (@cohort_ids)` statement to the SQL [here](https://github.com/darwin-eu-dev/TreatmentPatterns/blob/main/R/helperFunctions.R#L25).

**Comment by mvankessel-EMC** [comment]
Adressed in commit: 917156df8e6ec20b7f6e02c51bc30e33ccc8379f
