### ISSUE TITLE
Error when running TreatmentPatterns? 

### ISSUE THREAD

**Issue by SophieScanlon** [darwin-eu-dev/TreatmentPatterns#154]
Apologies if this is not the right place to ask, but I've been getting an error when I try to run TreatmentPatterns using code in the package information.

I've tried running the code from here https://darwin-eu-dev.github.io/TreatmentPatterns/articles/TreatmentPatternsStudy.html#step-4-execute-study (as below)

dataSettings <- createDataSettings(OMOP_CDM = FALSE,
                                   cohortLocation =
                                     file.path(system.file(package = "TreatmentPatterns"),
                                               "examples", "other format", "inst",
                                               "cohorts", "input_cohorts.csv"))

cohortSettings <-
  createCohortSettings(
    targetCohorts = data.frame(cohortId = c(1),
                               cohortName = c('Hypertension')),
    eventCohorts = data.frame(cohortId = c(10, 11, 12, 13, 14),
                              cohortName = c('Hydrochlorothiazide', 'Metorolol',
                                             'Amlodipine', 'Lisinopril', 'Losartan')),
    cohortsFolder = file.path(system.file(package = "TreatmentPatterns"),
                              "examples", "other format", "inst", "cohorts"))

pathwaySettings <- createPathwaySettings(targetCohortId = 1, eventCohortIds = c(10, 11, 12, 13, 14))

saveSettings <- createSaveSettings(databaseName = "IPCI", rootFolder = getwd())

executeTreatmentPatterns(dataSettings = dataSettings,
                                            cohortSettings = cohortSettings,
                                            pathwaySettings = pathwaySettings,
                                            saveSettings = saveSettings)

But I get the following error:
 
Warning: Error in &&: 'length = 3' in coercion to 'logical(1)'
  3: shiny::runApp
  2: TreatmentPatterns::launchResultsExplorer
  1: executeTreatmentPatterns
Error in is.call(funBody[[idx]]) && as.character(funBody[[idx]][[1]]) ==  : 
  'length = 3' in coercion to 'logical(1)'

Any help would be much appreciated, Thanks, Sophie

**Comment by mvankessel-EMC** [comment]
Hi @SophieScanlon, this approach is outdated with current version of TreatmentPatterns for DARWIN, it is also not available anymore on the latest [package website](https://darwin-eu-dev.github.io/TreatmentPatterns/).

I would suggest one of the following solutions: **1)** following the updated [instructions](https://darwin-eu-dev.github.io/TreatmentPatterns/articles/DarwinTreatmentPatternsStudy.html), if whatever you're trying to do is DARWIN related; or **2)** Use the original version found [here](https://github.com/mi-erasmusmc/TreatmentPatterns), with the instructions found [here](https://github.com/mi-erasmusmc/TreatmentPatterns/blob/master/docs/TreatmentPatternsStudy.pdf).
