### ISSUE TITLE
Looking for cdm_source in results schema

### ISSUE THREAD

**Issue by schuemie** [darwin-eu-dev/TreatmentPatterns#160]
I think this is a bug: my CDM schema has a `cdm_source` table, but my results schema (where the cohorts live) does not. But [this line](https://github.com/darwin-eu-dev/TreatmentPatterns/blob/main/R/R6-CDMInterface.R#L210) is looking for `cdm_source` in the results schema, causing a `relation "scratch_mschuemi.cdm_source" does not exist` error.

**Comment by mvankessel-EMC** [comment]
You are right, this should be de CDM schema instead. Thanks!

**Comment by mvankessel-EMC** [comment]
Addressed in 475ca2121ec510b71435a31f61bb1a7891b2a9e1
