### ISSUE TITLE
Document `cohorts` argument of `executeTreatmentPatterns()`

### ISSUE THREAD

**Issue by schuemie** [darwin-eu-dev/TreatmentPatterns#161]
The `executeTreatmentPatterns()` function has a `cohorts` argument. Currently, the [documentation](https://darwin-eu-dev.github.io/TreatmentPatterns/reference/executeTreatmentPatterns.html) only says this needs to be `data.frame`. It would be helpful to document which columns are expected (and what values are allowed for the `type` columns).

**Comment by mvankessel-EMC** [comment]
This is addressed in the version I'm pushing to CRAN. This should be resolved soon (https://github.com/darwin-eu-dev/TreatmentPatterns/blob/rc/man/executeTreatmentPatterns.Rd#L29-L36C3).
