### ISSUE TITLE
createSunburstPlot() like function that returns a HTML object

### ISSUE THREAD

**Issue by cbarbozaerasmus** [darwin-eu-dev/TreatmentPatterns#164]
Currently, the ´createSunburstPlot()´ saves a HTML file, from which a webshot is taken with ´saveAsFile()´, and then ReportGenerator shows that image in preview. 

It would be convinient to have a ´createSunburstPlot()´ like function that returns an HTML object to show in the preview of the shiny app. 

Then use ´saveAsFile()´ just to generate the image file that is printed in the report.

**Comment by mvankessel-EMC** [comment]
Addressed in: https://github.com/darwin-eu-dev/TreatmentPatterns/commit/067357c5351a6fda8a4ae322bd96bdf535a2ebc5

@cbarbozaerasmus Could you try out the following dummy code?

```r
treatmentPatwhays <- data.frame(
  path = c("Acetaminophen", "Acetaminophen-Amoxicillin+Clavulanate",
           "Acetaminophen-Aspirin", "Amoxicillin+Clavulanate", "Aspirin"),
  freq = c(206, 6, 14, 48, 221),
  sex = rep("all", 5),
  age = rep("all", 5),
  index_year = rep("all", 5)
)

createSunburstPlot(
  treatmentPatwhays,
  returnHTML = TRUE
)
```

**Comment by cbarbozaerasmus** [comment]
I can create the HTML response with the new parameter. However, the html doesn't produce a sunburst chart inside the shiny app. I see that there is another template (sunburst_shiny.html). Do you think template file might work better?

![image](https://github.com/darwin-eu-dev/TreatmentPatterns/assets/113351542/ef34aed4-c807-471c-898d-22481fb4538a)

**Comment by mvankessel-EMC** [comment]
> I can create the HTML response with the new parameter. However, the html doesn't produce a sunburst chart inside the shiny app. I see that there is another template (sunburst_shiny.html). Do you think template file might work better?
> 
> ![image](https://user-images.githubusercontent.com/113351542/265490643-ef34aed4-c807-471c-898d-22481fb4538a.png)


The Sunburst is there, there is just not enough space for the plot and legend.

The issue with the shiny template is, is that it does not have a legend, rendering the sunburst meaningless. So in this (https://github.com/darwin-eu-dev/TreatmentPatterns/commit/a2c405b31fbf74000e8d783c1fb424dad7c48f8c) commit I've changed the templates. When `returnHTML` is set to `TRUE` a list will be returned with the sunburst-html and the legend-html.
