### ISSUE TITLE
createSankeyDiagram() like function that returns a googleVis::gvisSankey object

### ISSUE THREAD

**Issue by cbarbozaerasmus** [darwin-eu-dev/TreatmentPatterns#165]
Currently, the ´createSankeyDiagram()´ saves an HTML file. 

In ReportGenerator, I[ modified the function](https://github.com/darwin-eu-dev/ReportGenerator/blob/034680b0a164b97488717f137ae2be8cc63fc9aa/R/treatmentPatterns.R#L17C4-L17C9 ) so it returns a googleVis object, which can be rendered by Shiny with htmlOutput. 

It would be convinient to have a ´createSunburstPlot()´ that returns an the googleVis::gvisSankey object to show in the preview of the shiny app.

**Comment by mvankessel-EMC** [comment]
Addressed in: https://github.com/darwin-eu-dev/TreatmentPatterns/commit/4b726b018cc7ac990c4ce729200ae08472161285

**Comment by mvankessel-EMC** [comment]
@cbarbozaerasmus Could you try out the following dummy code, and see if it is how you like it?

```r
treatmentPathways <- data.frame(
  path = c("Acetaminophen", "Acetaminophen-Amoxicillin+Clavulanate",
           "Acetaminophen-Aspirin", "Amoxicillin+Clavulanate", "Aspirin"),
  freq = c(206, 6, 14, 48, 221),
  sex = rep("all", 5),
  age = rep("all", 5),
  index_year = rep("all", 5)
)

html <- createSankeyDiagram(
  treatmentPathways,
  outputHTML = TRUE
)
```

**Comment by cbarbozaerasmus** [comment]
It works, thanks a lot!

The final parameter will be outputHTML or returnHTML?
