### ISSUE TITLE
Performance issues with larger databases

### ISSUE THREAD

**Issue by edward-burn** [darwin-eu-dev/TreatmentPatterns#171]
Similar to #143, I'm hitting performance issues when trying to use TreatmentPatterns on larger data. For example in a dataset with 34 million people, but a study cohort of more like 60,000, it took a few days to run one call to executeTreatmentPatterns. I think @kimlopezguell and @ablack3 have also faced some similar issues when trying to use the package.

@mvankessel-EMC I know before the package would read all required data out of the database into R , but I'm not sure if it still does? I'm wondering if something like cohortIntersect from PatientProfiles https://darwin-eu-dev.github.io/PatientProfiles/reference/addCohortIntersect.html could help to do some of the steps before collecting data into R (as this is probably where it is problematic in that the cohort tables can still be extremely large) as this would work on the database side?

Maybe the best place to start though would be benchmarking some of the specific steps run within executeTreatmentPatterns? In particular it seemed for me it was the step "Construct treatment pathways, this may take a while for larger datasets" that took by far the longest (apologies that I don't have any log file with the timings, but can run any benchmarking that can help)

**Comment by ablack3** [comment]
Yea it would be nice to at least have the option to keep the cohort table in The database. 

I've looked into a cross platform string_agg sql function that might help. 

But we should actually get an idea of the best possible performance for this algorithm. We also need better large test datasets I think.

**Comment by daniprietoalhambra** [comment]
@ilovemane @edward-burn could we try this in the ongoing DARWIN EU studies? if this solution does not work (or if it does not speed things up) in DARWIN EU data partners, then I would suggest we try the solution suggested by Ed above using PatientProfiles - cohortIntersect @mvankessel-EMC

**Comment by daniprietoalhambra** [comment]
also have you tried that solution in IPCI yourself, @mvankessel-EMC ? does it improve things?

**Comment by mvankessel-EMC** [comment]
> also have you tried that solution in IPCI yourself, @mvankessel-EMC ? does it improve things?

On a cohort of roughly 10000 persons it seems to run roughly 25% faster.

Keep in mind that the optimizations made, were specifically about moving / copying data around in Andromeda, so this change will be more drastic on larger datasets.

**Comment by mvankessel-EMC** [comment]
Cesar is also running a TreatmentPatterns study on IPCI right now. so I asked him to compare to the new version aswel.

**Comment by mvankessel-EMC** [comment]
Respond here: #143

**Comment by PRijnbeek** [comment]
> Yea it would be nice to at least have the option to keep the cohort table in The database.
> 
> I've looked into a cross platform string_agg sql function that might help.
> 
> But we should actually get an idea of the best possible performance for this algorithm. We also need better large test datasets I think.

I think CPRD is the best large test database we have. We do need to start testing on it much earlier.

**Comment by daniprietoalhambra** [comment]
> Similar to #143, I'm hitting performance issues when trying to use TreatmentPatterns on larger data. For example in a dataset with 34 million people, but a study cohort of more like 60,000, it took a few days to run one call to executeTreatmentPatterns. I think @KimLopezGuell and @ablack3 have also faced some similar issues when trying to use the package.
> 
> @mvankessel-EMC I know before the package would read all required data out of the database into R , but I'm not sure if it still does? I'm wondering if something like cohortIntersect from PatientProfiles https://darwin-eu-dev.github.io/PatientProfiles/reference/addCohortIntersect.html could help to do some of the steps before collecting data into R (as this is probably where it is problematic in that the cohort tables can still be extremely large) as this would work on the database side?
> 
> Maybe the best place to start though would be benchmarking some of the specific steps run within executeTreatmentPatterns? In particular it seemed for me it was the step "Construct treatment pathways, this may take a while for larger datasets" that took by far the longest (apologies that I don't have any log file with the timings, but can run any benchmarking that can help)

@mvankessel-EMC - I notice this issue was closed but I don't think it's resolved. @edward-burn 's suggestion here is a really useful one. All the studies we are doing in DARWIN EU to date would benefit from the use of cohortIntersect to 'subset' the analysis to people with a given index condition/indication. this could improve the performance of our analyses quite dramatically, so I would not ditch this idea, independently of other improvements like discussed elsewhere. Or have I missed something?

**Comment by mvankessel-EMC** [comment]
> > Similar to #143, I'm hitting performance issues when trying to use TreatmentPatterns on larger data. For example in a dataset with 34 million people, but a study cohort of more like 60,000, it took a few days to run one call to executeTreatmentPatterns. I think @KimLopezGuell and @ablack3 have also faced some similar issues when trying to use the package.
> > @mvankessel-EMC I know before the package would read all required data out of the database into R , but I'm not sure if it still does? I'm wondering if something like cohortIntersect from PatientProfiles https://darwin-eu-dev.github.io/PatientProfiles/reference/addCohortIntersect.html could help to do some of the steps before collecting data into R (as this is probably where it is problematic in that the cohort tables can still be extremely large) as this would work on the database side?
> > Maybe the best place to start though would be benchmarking some of the specific steps run within executeTreatmentPatterns? In particular it seemed for me it was the step "Construct treatment pathways, this may take a while for larger datasets" that took by far the longest (apologies that I don't have any log file with the timings, but can run any benchmarking that can help)
> 
> @mvankessel-EMC - I notice this issue was closed but I don't think it's resolved. @edward-burn 's suggestion here is a really useful one. All the studies we are doing in DARWIN EU to date would benefit from the use of cohortIntersect to 'subset' the analysis to people with a given index condition/indication. this could improve the performance of our analyses quite dramatically, so I would not ditch this idea, independently of other improvements like discussed elsewhere. Or have I missed something?

@daniprietoalhambra

This is a similar issue to the #143. I like to keep everything in one place, regarding performance on large data. This keeps it clear for me, and there is then one place where people can follow along with the discussion.

Closing the issue should prevent (clearly not) people discussing similar issues in two separate threads.

Also:
1. I have responded in the other issue (#143) to Ed, you, and Adam regarding Ed's suggestion.
> @edward-burn @daniprietoalhambra @ablack3 Added some more filtering in commit [b2cdc21](https://github.com/darwin-eu-dev/TreatmentPatterns/commit/b2cdc21969327ef8fa1f3d89028b308c26c512c0)
> 
> Subjects in an `event`/`exit` cohort should now also exist in the `target` cohort, before the data is pulled into R.

2. On the closing comment, I've linked #143 and requested to respond there instead.


> Respond here: #143
> 
>...
>...
