### ISSUE TITLE
DatabaseConnector or CDMConnector in suggests

### ISSUE THREAD

**Issue by edward-burn** [darwin-eu-dev/TreatmentPatterns#173]
At the moment TreatmentPatterns supports either DatabaseConnector or CDMConnector, but with DatabaseConnector in imports while CDMConnector is in suggests. But one problem I had with this is that when I run the analysis with CDMConnector, deploying an app with TreatmentPatterns, even just to call createSunburstPlot, requires the shiny server to have java installed (which is problematic for ours at the moment).

@mvankessel-EMC What about both DatabaseConnector and CDMConnector to be in suggests? Then if someone goes down the CDMConnector route they wouldn't need the heavy dependencies.

**Comment by mvankessel-EMC** [comment]
I agree, done one `dev` d8265f862160d7004bfb6ec4c6ea07bb0266b230

**Comment by edward-burn** [comment]
@mvankessel-EMC great, I think SQL render would also need to be in suggests to remove the java dependency for a shiny app?

**Comment by mvankessel-EMC** [comment]
Yes, done 62061d26e64906a13765d5997a7d5ba6bf137d85.
