### ISSUE TITLE
Fail to compute Age in treatment pattern

### ISSUE THREAD

**Issue by ilovemane** [darwin-eu-dev/TreatmentPatterns#175]
I came across this problem, for my cohort treatmentPattern fail to compute age. I found out the reason is in my database the birth_datetime field is all NA.  And this field is used to generate the age in treatmentPattern. https://github.com/darwin-eu-dev/TreatmentPatterns/blob/dev/R/R6-CDMInterface.R#L223-L244

I suggest write something to generate the age base on the year_of_birth if birth_datetime is missing? Or you can use the addAge  function in PatientProfiles, instead of calculating in the function yourself. As addAge can handle missing data.

@catalamarti @edward-burn @mvankessel-EMC 

![image](https://github.com/darwin-eu-dev/TreatmentPatterns/assets/58779940/2295470a-d72b-4a7b-bee7-5e3a6c83c92f)

**Comment by catalamarti** [comment]
hi @mvankessel-EMC `birth_datetime` is not a required filed in person table (https://ohdsi.github.io/CommonDataModel/cdm54.html#PERSON ). In fact the only one required is `year_of_birth`. This has been implmented in `PatientProfiles::addAge()` https://darwin-eu-dev.github.io/PatientProfiles/reference/addAge.html I would recommend using that function or at least using the same logic to compute age.
@ilovemane @edward-burn

**Comment by mvankessel-EMC** [comment]
> hi @mvankessel-EMC `birth_datetime` is not a required filed in person table (https://ohdsi.github.io/CommonDataModel/cdm54.html#PERSON ). In fact the only one required is `year_of_birth`. This has been implmented in `PatientProfiles::addAge()` https://darwin-eu-dev.github.io/PatientProfiles/reference/addAge.html I would recommend using that function or at least using the same logic to compute age. @ilovemane @edward-burn

Thanks @catalamarti, I'll look into an update that uses the required `year_of_birth`.

**Comment by ilovemane** [comment]
@mvankessel-EMC this is fixed now! Thanks
