### ISSUE TITLE
package installation failed - R 4.0

### ISSUE THREAD

**Issue by ginberg** [darwin-eu-dev/TreatmentPatterns#181]
@mvankessel-EMC  One of the data partners tried to install the latest version of TreatmentPatterns but it failed with the error below.
I think you need to set the minimum version of R in the DESCRIPTION to 4.1 since you are using the native pipe operator which has been introduced in that version.
See also 
https://github.com/harrelfe/Hmisc/issues/159

```
Error: Error installing package 'TreatmentPatterns':
=============================================
 
* installing *source* package ‘TreatmentPatterns’ ...
** package ‘TreatmentPatterns’ successfully unpacked and MD5 sums checked
** using staged installation
** R
Error in parse(outFile) :
  /data01/Rtmp5jfwZe/R.INSTALL26fffa5b9f8087/TreatmentPatterns/R/createSankeyDiagram.R:209:32: unexpected '>'
208:  
209:   n <- treatmentPathways$path |>
                                    ^
ERROR: unable to collate and parse R files for package ‘TreatmentPatterns’
* removing ‘/home/projects/darwin/studies/year2/P2-C1-008-MDD/P2-C1-008-DUS-MDD-main/renv/staging/1/TreatmentPatterns’
install of package 'TreatmentPatterns' failed [error code 1]
```

**Comment by mvankessel-EMC** [comment]
Thanks @ginberg, in the SRS it specifically states that `TreatmentPatterns` is at least compatible with R 4.2.1. `DrugUtilization` and `IncidencePrevalence` state the same version (I'm assuming more packages as well).

I'll update the minimum version to 4.2.1 in the DESCRIPTION-file.

**Comment by mvankessel-EMC** [comment]
Updated in 7573aa3a175112704cba604cc0c08a0fc36ffaf6
