### ISSUE TITLE
Correction for documentation on executeTreatmentPatterns

### ISSUE THREAD

**Issue by mderidder95** [darwin-eu-dev/TreatmentPatterns#187]
The cohort names assigned in the code below do not agree with the code above.
Cohort 2 should be "Aspirin" and 3 "Acetaminophen".

https://github.com/darwin-eu-dev/TreatmentPatterns/blob/4cf68497fb20127958f80ead35a6ef7788a92463/R/executeTreatmentPatterns.R#L120-L124

**Comment by mvankessel-EMC** [comment]
I've entirely re-done this documentation, as it was very outdated. Please see [the updated example](https://darwin-eu-dev.github.io/TreatmentPatterns/reference/executeTreatmentPatterns.html).

**Comment by mvankessel-EMC** [comment]
Added into latest CRAN release (2.6.2)
