### ISSUE TITLE
Typo in name result file

### ISSUE THREAD

**Issue by mderidder95** [darwin-eu-dev/TreatmentPatterns#188]
https://github.com/darwin-eu-dev/TreatmentPatterns/blob/4cf68497fb20127958f80ead35a6ef7788a92463/R/export.R#L168-L169

**Comment by mvankessel-EMC** [comment]
Fixed on dev: ba8a4e45b8a36c54bb0b3166b7d7d09702ec54c2

**Comment by mvankessel-EMC** [comment]
Added into latest CRAN release (2.6.2)
