### ISSUE TITLE
Denominator in treatment pattern package

### ISSUE THREAD

**Issue by Verhamme** [darwin-eu-dev/TreatmentPatterns#189]
We have used the treatment pattern package to check the number and percentage of individuals following a diagnosis. 
Numbers were investigated at different times of follow-up - so from start of diagnosis up to 4 weeks of fup, 12 weeks of fup etc. 
You would assume that the number of individuals with a specific diagnosed and being followed up up to 12 weeks would be similar or smaller than the numbers at 4 weeks of fup but this is not the case (because of people dying, leaving practice, etc. ) In contrast, the numbers were increasing meaning that I had more individuals at 12 weeks of fup then at 4 weeks of fup. 
Can you please explore

**Comment by mvankessel-EMC** [comment]
Cross post from #191

> I've added 3 censoring methods in a4dab3ca05635ae28d8809eb858dd3a017db4ea0.
> 
> >censorType
> >(character(1))
> >
> >"cellCount"
> >Censors pathways <cellCount to cellCount.
> >
> >"remove"
> >Censors pathways <cellCount by removing them completely.
> >
> >"mean"
> >Censors pathways <cellCount to the mean of all frequencies below cellCount
> 
> See [the help](https://darwin-eu-dev.github.io/TreatmentPatterns/reference/export.html) page for `export()`
