### ISSUE TITLE
Report pathways with < minCount in the results.

### ISSUE THREAD

**Issue by mderidder95** [darwin-eu-dev/TreatmentPatterns#191]
To align with other DARWIN packages and inform about existing but too small pathways.

**Comment by mvankessel-EMC** [comment]
I've added 3 censoring methods in a4dab3ca05635ae28d8809eb858dd3a017db4ea0.

>censorType
>(character(1))
>
>"cellCount"
>Censors pathways <cellCount to cellCount.
>
>"remove"
>Censors pathways <cellCount by removing them completely.
>
>"mean"
>Censors pathways <cellCount to the mean of all frequencies below cellCount

See [the help](https://darwin-eu-dev.github.io/TreatmentPatterns/reference/export.html) page for `export()`

**Comment by mderidder95** [comment]
There seems to be a typo in the parameters choices:

https://github.com/darwin-eu-dev/TreatmentPatterns/blob/a4dab3ca05635ae28d8809eb858dd3a017db4ea0/R/export.R#L71

**Comment by mvankessel-EMC** [comment]
> There seems to be a typo in the parameters choices:
> 
> https://github.com/darwin-eu-dev/TreatmentPatterns/blob/a4dab3ca05635ae28d8809eb858dd3a017db4ea0/R/export.R#L71

Could you 1) make a new issue for this, and 2) explicitly say what the typo is.
