### ISSUE TITLE
Too small width for legend

### ISSUE THREAD

**Issue by mderidder95** [darwin-eu-dev/TreatmentPatterns#192]
![test1](https://github.com/darwin-eu-dev/TreatmentPatterns/assets/57101589/e2921fa5-047a-44ba-b210-bebb657007e7)

**Comment by mvankessel-EMC** [comment]
In a4dab3ca05635ae28d8809eb858dd3a017db4ea0 you can set the legend width like so:

```r
createSunburstPlot2(
  treatmentPathways = data,
  legend = list(w = 400)
)
```

Any of the parameters of [`sunburstR::sunburst`](https://timelyportfolio.github.io/sunburstR/reference/sunburst.html) can be passed.
