### ISSUE TITLE
Labeling of age groups in accordance with other DARWIN packages

### ISSUE THREAD

**Issue by mderidder95** [darwin-eu-dev/TreatmentPatterns#194]
Labeling of age groups in other DARWIN packages is 0-9, 10-19, 20-29 etc.

**Comment by mderidder95** [comment]
This is just about alignment between the DARWIN packages. In IncidencePrevalence and PatientProfiles, agegroup 0-10 means that children with age 10 are included. See for example documentation of function generateDenominatorCohortSet in IncidencePrevalence: 
ageGroup: A list of age groups for which cohorts will be generated. A value of list(c(0,17), c(18,30)) would, for example, lead to the creation of cohorts for those aged from 0 to 17, and from 18 to 30.

In TreatmentPatterns, labels of 'age' in treatmentPathways.csv, 0-10 means up to 10, 10 not included.

**Comment by mvankessel-EMC** [comment]
Thank you Maria, this has been changed in 2.6.1.
