### ISSUE TITLE
noPath in strata

### ISSUE THREAD

**Issue by rossdwilliams** [darwin-eu-dev/TreatmentPatterns#195]
**Is your feature request related to a problem? Please describe.**
Currently when we do a stratified analysis we only see event cohorts in these strata but not the untreated patients in the target cohorts. This information is available in the non stratified analysis and it would be good to have it for all analyses.

**Describe the solution you'd like**
When performing an age or sex strata, having the noPaths in these strata (also maybe in combinations of these strata as well) would be great.

**Additional context**
This has been requested for a couple of the on going studies

**Comment by mvankessel-EMC** [comment]
`None` paths are now supported per strata in a4dab3ca05635ae28d8809eb858dd3a017db4ea0.
