### ISSUE TITLE
Inconsistency for argument options in export function

### ISSUE THREAD

**Issue by mderidder95** [darwin-eu-dev/TreatmentPatterns#198]
Probably the documentation for argument `censorType` of function `export` has a typo. Here `cellCount` is mentioned, while it should be `minCellCount `?

**Comment by mvankessel-EMC** [comment]
Changed in: f0e2b2a23f4ab72d408fea29d4fbc5067a67b209

**Comment by mvankessel-EMC** [comment]
Added into latest CRAN release (2.6.2)
