### ISSUE TITLE
Target cohort not allowed to have same start and end date?

### ISSUE THREAD

**Issue by schuemie** [darwin-eu-dev/TreatmentPatterns#199]
[This line](https://github.com/darwin-eu-dev/TreatmentPatterns/blob/dev/inst/sql/selectData.sql#L23) means that no cohort is allowed that has `cohort_start_date` = `cohort_end_date`. I can understand why you'd want that for the exposure cohorts, but it is also applied to the target cohort. 

My target cohort (hypertension) happens to be defined as having length = 0, which you could argue is wrong (end date should really be end of observation), but it took me a long time to figure out that was the reason the analysis was not producing results. And I don't believe the target cohort end date is used anywhere else? 

Could perhaps the restriction be lifted for the target cohort, or else a warning produced when all entries in the target cohort have length 0?

**Comment by mvankessel-EMC** [comment]
I looked back into the [original code](https://github.com/mi-erasmusmc/TreatmentPatterns/blob/master/R/ConstructPathways.R#L200-L205C2), this seems to be a bug. Changed in: a3b78c38c13a5a63db0373b7342fb1916396567c

**Comment by mvankessel-EMC** [comment]
Added into latest CRAN release (2.6.2)
