### ISSUE TITLE
use cohortGenerator

### ISSUE THREAD

**Issue by rossdwilliams** [darwin-eu-dev/TreatmentPatterns#2]
**Is your feature request related to a problem? Please describe.**
The darwin-eu standard cohort creation mechanism on a database will be using cohortGenerator package, currently this is ot the case in treatmentPatterns

**Describe the solution you'd like**
Removal of custom cohort generation code and standardising to using cohortgenerator package

**Additional context**
This is a standardisation procedure

**Comment by mvankessel-EMC** [comment]
CohortGenerator seems to have issues running in SQL Server. As [reported](https://github.com/OHDSI/CohortGenerator/issues/64) by Cesar. I am running into the same issue when running it on Synthea.

**Comment by mvankessel-EMC** [comment]
Fixed in: https://github.com/OHDSI/DatabaseConnector/issues/215
