### ISSUE TITLE
Exporting figures to word/ pdf

### ISSUE THREAD

**Issue by edward-burn** [darwin-eu-dev/TreatmentPatterns#204]
@mvankessel-EMC at the moment createSunburstPlot and createSankeyDiagram provide nice html output, but is there already a recommended way to export these for word/ pdf (that could be used for example in a RMD file that renders to one of these) or, if not, could this be added (perhaps an argument to the function)?

**Comment by mvankessel-EMC** [comment]
Both plots are `htmlwidget` objects, which renders the HTML when used in RMarkdown. When rendered to a PDF or Word-document, it will render a static version of the plot. See the following example rmd-file.
