### ISSUE TITLE
Treatment Pathways Seemingly Does Not Generate Pathways

### ISSUE THREAD

**Issue by TheCedarPrince** [darwin-eu-dev/TreatmentPatterns#207]
**Describe the bug**

I have generated 4 cohorts that I have passed into Treatment Pathways, and I get this message after running `computePathways`:

```
Construct treatment pathways, this may take a while for larger datasets.
Original number of rows: 0
After eraCollapseSize: 0
After combinationWindow: 0
Time needed to execute combination window 0.00844308535257975
Order the combinations.
After filterTreatments: 0
constructPathways done.
``` 

I followed the instructions exactly as per the documentation for TreatmentPatterns 2.6.2 and I do not understand why this is not generating any pathways. My cohorts are rather small (only about ~500 with the smallest having only ~100 patients) but I'd imagine this shouldn't matter. 

Could it be that I did something wrong with my cohort definitions?

**To Reproduce**

Here were the cohorts I used:

- Target: [Depression](https://atlas-demo.ohdsi.org/#/cohortdefinition/1778401)
- Event: [Fluoxetine Exposure](https://atlas-demo.ohdsi.org/#/cohortdefinition/1788539)
- Event: [Sertraline Exposure](https://atlas-demo.ohdsi.org/#/cohortdefinition/1788538)
- Event: [Duloxetine Exposure](https://atlas-demo.ohdsi.org/#/cohortdefinition/1788540)

And here is the code I used:

```R
library(dplyr)
library(CirceR)
library(DatabaseConnector)
library(tibble)
library(TreatmentPatterns)

Sys.setenv("DATABASECONNECTOR_JAR_FOLDER" = "driver")
connectionDetails <- createConnectionDetails(dbms="postgresql", 
                                             server="localhost/synthea",
                                             user="thecedarprince",
                                             password="")
conn <- connect(connectionDetails)

cohorts <- tibble(cohortId = c(1,2,3,4), cohortName = c("Depression","Duloxetine","Fluoxetine", "Sertraline"), type = c("target", "event", "event", "event"))
cohorts <- cohorts  %>% mutate(across(cohortId, as.integer))

test <- computePathways(
  cohorts = cohorts,
  cohortTableName = "cohort",
  connectionDetails = connectionDetails,
  cdmSchema = "omop",
  resultSchema = "omop"
)
```

Also, if you want to fully reproduce this at all, here is the code I used to generate my cohorts:

```R
# Fill the cohort set using  cohorts included in this 
# package as an example
definition <- "depression.json"
cohortName <- tools::file_path_sans_ext(basename(definition))
cohortJson <- readChar(definition, file.info(definition)$size)
cohortExpression <- CirceR::cohortExpressionFromJson(cohortJson)
cohortSql <- CirceR::buildCohortQuery(cohortExpression, options = CirceR::createGenerateOptions(generateStats = FALSE))

# Create the cohort tables to hold the cohort generation results
cohortTableNames <- CohortGenerator::getCohortTableNames(cohortTable = "cohort")
CohortGenerator::createCohortTables(connectionDetails = connectionDetails,
                                                        cohortDatabaseSchema = "omop",
                                                        cohortTableNames = cohortTableNames)
# Generate the cohorts
cohortsGenerated <- CohortGenerator::generateCohortSet(connectionDetails = connectionDetails,
                                                       cdmDatabaseSchema = "omop",
                                                       cohortDatabaseSchema = "omop",
                                                       cohortTableNames = cohortTableNames,
                                                       cohortDefinitionSet = data.frame(cohortId = 1,
                                                           cohortName = cohortName, 
                                                           sql = cohortSql,
                                                           stringsAsFactors = FALSE))

# Fill the cohort set using  cohorts included in this 
# package as an example
definition <- "duloxetine.json"
cohortName <- tools::file_path_sans_ext(basename(definition))
cohortJson <- readChar(definition, file.info(definition)$size)
cohortExpression <- CirceR::cohortExpressionFromJson(cohortJson)
cohortSql <- CirceR::buildCohortQuery(cohortExpression, options = CirceR::createGenerateOptions(generateStats = FALSE))

# Generate the cohorts
cohortsGenerated <- CohortGenerator::generateCohortSet(connectionDetails = connectionDetails,
                                                       cdmDatabaseSchema = "omop",
                                                       cohortDatabaseSchema = "omop",
                                                       cohortTableNames = cohortTableNames,
                                                       cohortDefinitionSet = data.frame(cohortId = 2,
                                                           cohortName = cohortName, 
                                                           sql = cohortSql,
                                                           stringsAsFactors = FALSE))

# Fill the cohort set using  cohorts included in this 
# package as an example
definition <- "fluoxetine.json"
cohortName <- tools::file_path_sans_ext(basename(definition))
cohortJson <- readChar(definition, file.info(definition)$size)
cohortExpression <- CirceR::cohortExpressionFromJson(cohortJson)
cohortSql <- CirceR::buildCohortQuery(cohortExpression, options = CirceR::createGenerateOptions(generateStats = FALSE))

# Generate the cohorts
cohortsGenerated <- CohortGenerator::generateCohortSet(connectionDetails = connectionDetails,
                                                       cdmDatabaseSchema = "omop",
                                                       cohortDatabaseSchema = "omop",
                                                       cohortTableNames = cohortTableNames,
                                                       cohortDefinitionSet = data.frame(cohortId = 3,
                                                           cohortName = cohortName, 
                                                           sql = cohortSql,
                                                           stringsAsFactors = FALSE))

# Fill the cohort set using  cohorts included in this 
# package as an example
definition <- "sertraline.json"
cohortName <- tools::file_path_sans_ext(basename(definition))
cohortJson <- readChar(definition, file.info(definition)$size)
cohortExpression <- CirceR::cohortExpressionFromJson(cohortJson)
cohortSql <- CirceR::buildCohortQuery(cohortExpression, options = CirceR::createGenerateOptions(generateStats = FALSE))

# Generate the cohorts
cohortsGenerated <- CohortGenerator::generateCohortSet(connectionDetails = connectionDetails,
                                                       cdmDatabaseSchema = "omop",
                                                       cohortDatabaseSchema = "omop",
                                                       cohortTableNames = cohortTableNames,
                                                       cohortDefinitionSet = data.frame(cohortId = 4,
                                                           cohortName = cohortName, 
                                                           sql = cohortSql,
                                                           stringsAsFactors = FALSE))
```

**Desktop (please complete the following information):**
 - OS: Fedora 38

**Comment by mvankessel-EMC** [comment]
Thank you for reaching out!

It could be a couple things:
1. Subjects with depression (target) do not occur in your treatment cohorts (events).
2. Treatments happen before the occurrence of depression.

I'd like to verify a couple things:
1. Do records exist within the `cohort` table? Like you said we'd expect this to be between ~100 and 500.
```r
DatabaseConnector::renderTranslateQuerySql(
  connection = conn,
  sql = "SELECT cohort_definition_id, COUNT(*) FROM omop.cohort GROUP BY cohort_definition_id;"
)
```

2. Do people in your event cohorts also exist in your target cohorts? You can change the `cohort_definition_id` per event cohort.
```r
# Duloxetine in Depression
DatabaseConnector::renderTranslateQuerySql(
  connection = conn,
  sql = "
  SELECT subject_id
  FROM omop.cohort
  WHERE cohort_definition_id = 2 AND subject_id IN (
    SELECT subject_id
    FROM omop.cohort
    WHERE cohort_definition_id = 1
  );"
)
```

**Comment by TheCedarPrince** [comment]
Hey @mvankessel-EMC, 

I went through your debugging suggestions and here are my findings:

> Do records exist within the cohort table? Like you said we'd expect this to be between ~100 and 500.

This was a great thought. I checked my cohorts and they were all 100+.

> Do people in your event cohorts also exist in your target cohorts? You can change the cohort_definition_id per event cohort.

Sure enough, there were two events that had close to 0 patient overlaps. I removed those and these are now my patient counts with 200+ overlaps:

```
 cohort_definition_id | count 
----------------------+-------
                    1 |   291
                    2 |   424
```

> Treatments happen before the occurrence of depression.

I did a quick analysis and can confirm that the treatments do happen for my patients within the time period that they are part of the cohort (i.e. they are prescribed the drug I am considering as an event). 

---

After all this, I tried only having one target and event cohort (with 100's of overlaps) but I still do not see any pathways generating. What else should I be trying or checking? Do you think I did something wrong with my definitions? The ones I am using now are the [Depression](https://atlas-demo.ohdsi.org/#/cohortdefinition/1778401) one and the [Fluoxetine Exposure](https://atlas-demo.ohdsi.org/#/cohortdefinition/1788539)

Thanks!

**Comment by mvankessel-EMC** [comment]
I don't think it is the cohort definitions, as subjects for both cohorts show up in your cohort table. TreatmentPatterns is completly agnostic as to how you define your cohorts, as long as they pick up subjects for your cohort table.

I took another look at the logs TreatmentPatterns spat out during your initial run:
```
construct treatment pathways, this may take a while for larger datasets.
Original number of rows: 0
```

The fact that this is being printed means that there are records in your cohort table, but lost along the way when asserting that the start date of the target cohort is earlier than the start date of the event cohorts. And that the start date of the event cohort is earlier than the end date of the target cohort. To put it a little but more programmatic:
```
# targetStartDate: 2021-03-06
# eventStartDate: 2021-06-01
# targetEndDate: 2022-12-31

targetStartDate < eventStartDate AND eventStartDate < targetEndDate
```

This is because `includeTreatments = "startDate"`. You could try to set it to `"endDate"`, and alter your `periodPriorToIndex`.

**Comment by TheCedarPrince** [comment]
Hi @mvankessel-EMC 

Hooray! After fiddling a bunch with your suggestions on `periodPriorToIndex`, I was able to get pathways generated! This was the code that ended up working:

```R
test <- computePathways(
  cohorts = cohorts,
  cohortTableName = "cohort",
  maxPathLength = 5,
  connectionDetails = connectionDetails,
  cdmSchema = "omop",
  resultSchema = "omop",
  includeTreatments = "startDate",
  periodPriorToIndex = 18250
)
```

Out of curiosity, why do you think I had to set the `periodPriorToIndex` at all? I was under the impression that pathways would be generated by:

1. Look at my cohorts
2. Find when each patient starts in a cohort
3. Begin construction of pathways with respect to each patient entry
4. Look at occurrences of drug of interest per overlapping patient cohort
5. Generate pathways

But it seems like that is not truly how the algorithm underlying TreatmentPatterns works? 

P.S. I'll close this issue for now since my problem is solved, but thanks for all the help! :smile:

**Comment by mvankessel-EMC** [comment]
Looking back at your previous comment:

>I did a quick analysis and can confirm that the treatments do happen for my patients within the time period that they are part of the cohort (i.e. they are prescribed the drug I am considering as an event).

Do the event cohorts start during the target cohort? Or do they start before the target start date and look back and occur during the target cohort?

TreatmentPatterns assumes treatments start within the bounds of the target cohort for a patient.

![image](https://github.com/darwin-eu-dev/TreatmentPatterns/assets/112690347/40b5e695-b7c3-4306-8125-174cf3bd2459)
In this image, event 3 would not get picked up at all, unless the `periodPriorToIndex` is extended to i.e. 10.

I can point you to the [original article](https://www.sciencedirect.com/science/article/pii/S016926072200462X) that includes this image:
![image](https://github.com/darwin-eu-dev/TreatmentPatterns/assets/112690347/925465c0-4cfb-4811-9278-a05ccb8c2a1b)

Maybe this will clear up some things as to how the inclusion of events work.
