### ISSUE TITLE
Mismatch between targetCohort and treatmentHistory counts

### ISSUE THREAD

**Issue by solis9753** [darwin-eu-dev/TreatmentPatterns#215]
**Describe the bug**
Firstly, kudos on the developments of this package, looks great. I am not sure if this is caused due to a bug. 
I am trying to understand the results and I have noticed some inconsistencies between the initial number of the target cohorts and the actual numbers in the treatmentHistory. Below, there is a reprex following the package vignettes.

**To Reproduce**
``` r
library(CDMConnector)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(TreatmentPatterns)
#> Creating a generic function for 'toJSON' from package 'jsonlite' in package 'googleVis'

cohortSet <- readCohortSet(
  path = system.file(package = "TreatmentPatterns", "exampleCohorts")
)

con <- DBI::dbConnect(
  drv = duckdb::duckdb(),
  dbdir = eunomia_dir()
)

cdm <- cdmFromCon(
  con = con,
  cdmSchema = "main",
  writeSchema = "main"
)

cdm <- generateCohortSet(
  cdm = cdm,
  cohortSet = cohortSet,
  name = "cohort_table",
  overwrite = TRUE
)
#> ℹ Generating 8 cohorts
#> ℹ Generating cohort (1/8) - Acetaminophen)
#> ✔ Generating cohort (1/8) - Acetaminophen) [305ms]
#> 
#> ℹ Generating cohort (2/8) - Amoxicillin)
#> ✔ Generating cohort (2/8) - Amoxicillin) [186ms]
#> 
#> ℹ Generating cohort (3/8) - Aspirin)
#> ✔ Generating cohort (3/8) - Aspirin) [170ms]
#> 
#> ℹ Generating cohort (4/8) - Clavulanate)
#> ✔ Generating cohort (4/8) - Clavulanate) [151ms]
#> 
#> ℹ Generating cohort (5/8) - Death)
#> ✔ Generating cohort (5/8) - Death) [80ms]
#> 
#> ℹ Generating cohort (6/8) - Doxylamine)
#> ✔ Generating cohort (6/8) - Doxylamine) [155ms]
#> 
#> ℹ Generating cohort (7/8) - PenicillinV)
#> ✔ Generating cohort (7/8) - PenicillinV) [161ms]
#> 
#> ℹ Generating cohort (8/8) - ViralSinusitis)
#> ✔ Generating cohort (8/8) - ViralSinusitis) [224ms]
#> 

cohorts <- cohortSet %>%
  # Remove 'cohort' and 'json' columns
  select(-"cohort", -"json") %>%
  mutate(type = c("event", "event", "event", "event", "exit", "event", "event", "target")) %>%
  rename(
    cohortId = "cohort_definition_id",
    cohortName = "cohort_name",
  ) %>%
  select(cohortId, cohortName, type)

minEra60 <- computePathways(
  cohorts = cohorts,
  cohortTableName = "cohort_table",
  cdm = cdm,
  # Pathway settings
  periodPriorToIndex = 0,
  minEraDuration = 60,
  eraCollapseSize = 30,
  combinationWindow = 30,
  minPostCombinationDuration = 30,
  filterTreatments = "First",
  maxPathLength = 5
)
#> 
#> Construct treatment pathways, this may take a while for larger datasets.
#> Original number of rows: 336
#> After eraCollapseSize: 0
#> Selected 45 
#> out of 336 rows
#> Iteration: 1
#> Switches: 336
#> FRFS Combinations: 0
#> LRFS Combinations: 45
#> After combinationWindow: 291
#> Time needed to execute combination window 0.0499324162801107
#> Order the combinations.
#> After filterTreatments: 291
#> Adding drug sequence number.
#> After maxPathLength: 291
#> Adding concept names.
#> Ordering the combinations.
#> constructPathways done.

minEra60$targetCohorts %>%
  distinct(personId) %>%
  count()
#> [1] 2159

minEra60$treatmentHistory %>%
  distinct(personId) %>%
  count()
#> # Source:   SQL [1 x 1]
#> # Database: sqlite 3.40.0 [/var/folders/n5/v3hbbdqs0f554tk29kqb67040000gn/T//Rtmp87imVj/file693a36d5972e.sqlite]
#>       n
#>   <int>
#> 1   279
```

<sup>Created on 2024-02-07 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Expected behavior**
In general I don't expect that all people in my target cohort are receiving the specified treatments, therefore I am not expecting that all people in the target cohort will be present in the treatmentHistory. On the other hand, I would like to explicitly know the number of people that received treatment. From the above results, I am inferring that out of the 2159 people in the target cohort, only 279 get the treatments. Is this correct? Additionally, I am not sure how to find out how many people received treatments from the output, which causes further confussion (please see the **Additional Context** section)

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma 14.1.2

**Additional context**
When I export the results as suggested on the vignette, filter indexYear == "all", and sum the freq column I still get a different number. 

``` r
minEraCsv <- read.csv("minEra60_cellCount/treatmentPathways.csv")
minEraCsv |>
  dplyr::filter(indexYear == "all") |>
  dplyr::summarise(base::sum(freq))
#>   base::sum(freq)
#> 1           13258
```

<sup>Created on 2024-02-07 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by mvankessel-EMC** [comment]
Thank you for reaching out!

> From the above results, I am inferring that out of the 2159 people in the target cohort, only 279 get the treatments. Is this correct?

279 people have valid pathways. People might have received a treatment, but might be filtered out due to the parameters you set. As an example setting `minEraDuration = 60` will filter out any event that has a duration shorter than 60. So it is very possible that a person might be on Acetaminophen for 40 days, but is filtered out due to the duration being shorter than 60 days.

> Additionally, I am not sure how to find out how many people received treatments from the output, which causes further confussion (please see the Additional Context section)

So called `None` paths are included in the output. These are the number of people that do not have valid events. For example they might be filtered out due to the `minEraDuration`.

You can filter out these `None` paths like so, in your earlier example:
```r
minEraCsv <- read.csv("minEra60_cellCount/treatmentPathways.csv")
minEraCsv |>
  dplyr::filter(indexYear == "all", path != "None") |>
  dplyr::summarise(base::sum(freq))
```

I hope this help!

**Comment by mvankessel-EMC** [comment]
>I get a total frequency of 300. Shouldn't this number be 279, to match the people with valid treatment?

In the example you provided the minimum frequency is 5. I'm under the assumption that you set your `minCellCount = 5` in `export()` This would explain you the reported count is not equal to the expected count.

> Further, when I inspect the differences in the sex strata the total frequency is again some number which doesn't make sense (see the second example in the previous reprex). Inspecting the objects above it seems that the object with the sex strata prints the paths twice.

This is a known issue and has been resolved in the latest version of TreatmentPatterns (>=2.6.4).

**Comment by mvankessel-EMC** [comment]
Closing this, as it seems all your questions here are answered, if you have more feel free to open new issues.
