### ISSUE TITLE
Option to include events that have the same end day as the target cohort

### ISSUE THREAD

**Issue by ZorzArg** [darwin-eu-dev/TreatmentPatterns#239]
**Is your feature request related to a problem? Please describe.**
Currently, the package code includes event cohorts in its calculation that ended up to the target cohort start date but not including that day (that happens whether the **includeTreatments** argument is set at _endDate_ or _startDate_).

**Describe the solution you'd like**
It would be really helpful to add an argument in functions **computePathways** and/or **executeTreatmentPatterns** for the user to choose whether to include the end date or not.

**Describe alternatives you've considered**
One option is to change the target cohort definition (one of the event cohorts are added as an exit criterion which why we don't see patterns of that event; they exit the cohort once the had the event) but that seemed unacceptable for the study we are currently running.
Another option is to edit the R code myself but I wanted to check this with you in case such edit would impact the Treatment Patterns results.

**Additional context**
Not sure if it helps but the event cohort mentioned above is a procedure concept.

**Comment by mvankessel-EMC** [comment]
Let me confirm what you mean by an example:

``` r
library(TreatmentPatterns)
library(dplyr)
library(CDMConnector)

con <- DBI::dbConnect(duckdb::duckdb(), dbdir = eunomia_dir())
```

Let's say we have 4 cohorts; **Illness X** (target); **Procedure A** (event); **Procedure B** (event); and **Procedure C** (event).
``` r
cohorts <- data.frame(
  cohortId = c(1, 2, 3, 4),
  cohortName = c("Illness X", "Procedure A", "Procedure B", "Procedure C"),
  type = c("target", "event", "event", "event")
)
```

And the following cohort table:
| cohort_definition_id | subject_id | cohort_start_date | cohort_end_date |
| --- | --- | --- | --- |
| 1 | 5 | 2014-01-01 | 2014-01-31 |
| 2 | 5 | 2014-01-10 | 2014-01-31 |
| 3 | 5 | 2014-01-30 | 2014-01-30 |
| 4 | 5 | 2014-01-31 | 2014-01-31 |
 
```r
cohort_table <- dplyr::tribble(
  ~cohort_definition_id, ~subject_id, ~cohort_start_date,    ~cohort_end_date,
  # Illness X: from 1 Jan 2014 to 31 Jan 2014
  1,                     5,           as.Date("2014-01-01"), as.Date("2014-01-31"),
  # Procedure A: from 10 Jan 2014 to 31 Jan 2014
  2,                     5,           as.Date("2014-01-10"), as.Date("2014-01-31"),
  # Procedure B: from 30 Jan 2014 to 30 Jan 2014
  3,                     5,           as.Date("2014-01-30"), as.Date("2014-01-30"),
  # Procedure C: from 31 Jan 2014 to 31 Jan 2014
  4,                     5,           as.Date("2014-01-31"), as.Date("2014-01-31")
)
```

And we run our TreatmentPatterns analysis
```r
copy_to(con, cohort_table, overwrite = TRUE)

cdm <- cdmFromCon(
  con = con,
  cdmSchema = "main",
  writeSchema = "main",
  cohortTables = "cohort_table"
)

outputEnv <- TreatmentPatterns::computePathways(
  cohorts = cohorts,
  cohortTableName = "cohort_table",
  cdm = cdm,
  includeTreatments = "startDate",
  minEraDuration = 0,
  combinationWindow = 30,
  minPostCombinationDuration = 0
)
#> Construct treatment pathways, this may take a while for larger datasets.
#> Original number of rows: 2
#> After eraCollapseSize: 0
#> Selected 1 
#> out of 2 rows
#> Iteration: 1
#> Switches: 2
#> FRFS Combinations: 0
#> LRFS Combinations: 0
#> After combinationWindow: 2
#> Time needed to execute combination window 0.0340961496035258
#> Order the combinations.
#> After filterTreatments: 2
#> Adding drug sequence number.
#> After maxPathLength: 2
#> Adding concept names.
#> Ordering the combinations.
#> constructPathways done.
```

Our result contains Procedure A and Procedure B.
``` r

outputEnv$treatmentHistory %>%
  select("eventCohortId", "eventCohortName", "personId", "eventSeq")
#> # Source:   SQL [2 x 4]
#> # Database: sqlite 3.46.0 [C:\Users\MVANKE~1\AppData\Local\Temp\RtmpiyTPBb\file72d414331a44.sqlite]
#>   eventCohortId eventCohortName personId eventSeq
#>   <chr>         <chr>              <dbl>    <int>
#> 1 2             Procedure A            5        1
#> 2 3             Procedure B            5        2
```

``` r

DBI::dbDisconnect(con)
```

<sup>Created on 2024-06-26 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

And you would expect the following:
```r
#>   eventCohortId eventCohortName personId eventSeq
#>   <chr>         <chr>              <dbl>    <int>
#> 1 2             Procedure A            5        1
#> 2 3             Procedure B            5        2
#> 2 4             Procedure C            5        3
```

**Comment by ZorzArg** [comment]
Hi Maarten,

Thanks a lot for response. 

That's exactly what I meant.

At the moment, the packages includes events that started up to the target cohort's end date but not including that date i.e.

`event_cohort$start_date < target_cohort$end_date`

So, we would like to have an option to include events that started on the target cohort's end date (Procedure C in your example) turning the condition above to:

`event_cohort$start_date <= target_cohort$end_date`
