### ISSUE TITLE
Check function: doCombinationWindow

### ISSUE THREAD

**Issue by mvankessel-EMC** [darwin-eu-dev/TreatmentPatterns#32]
1. Function documentation in order with SRS (Roxygen2)
2. Functionality in order with function documentation
3. Unit test in order with TestPlan (usethis, testthat)
4. Code review of function (other dev than whoever picked up this ticket) (lintr)

**Comment by mvankessel-EMC** [comment]
Test variables are setup. Two basic tests exists, "void" and "minimal". More extensive tests have to be written.

**Comment by ablack3** [comment]
I wrote several failing tests for this function which indicates to me that the output is not correct (or what I'm expecting). https://github.com/darwin-eu-dev/TreatmentPatterns/pull/97

@mvankessel-EMC Can we discuss the expected behavior of this function somewhere?

**Comment by ablack3** [comment]
Here are some reprex's of unexpected results

# Example 1: combinationWindow does not work as expected.

``` r
library(TreatmentPatterns)
#> Warning: replacing previous import 'data.table::last' by 'dplyr::last' when
#> loading 'TreatmentPatterns'
#> Warning: replacing previous import 'data.table::first' by 'dplyr::first' when
#> loading 'TreatmentPatterns'
#> Warning: replacing previous import 'data.table::between' by 'dplyr::between'
#> when loading 'TreatmentPatterns'
#> Creating a generic function for 'toJSON' from package 'jsonlite' in package 'googleVis'
treatment_history <- tibble::tribble(
  ~event_cohort_id,     ~person_id,   ~event_start_date,  ~event_end_date,
  101,                   1,           "2020-05-01",       "2020-06-01",
  102,                   1,           "2020-05-01",       "2020-06-01"
) %>%
  dplyr::mutate(dplyr::across(dplyr::ends_with("date"), as.Date)) %>% 
  data.table::data.table()

treatment_history[,
                  `:=`(duration_era = difftime(event_end_date, event_start_date, units = "days"),
                       index_year = as.numeric(format(event_start_date, "%Y")))]

result <- TreatmentPatterns:::doCombinationWindow(treatment_history, 
                                                  combinationWindow = 100, 
                                                  minPostCombinationDuration = 1)
#> [1] "Iteration 1 modifying  1 selected rows out of 2: 0 switches, 1 combinations FRFS and 0 combinations LRFS"
#> Currently in a tryCatch or withCallingHandlers block, so unable to add global calling handlers. ParallelLogger will not capture R messages, errors, and warnings, only explicit calls to ParallelLogger. (This message will not be shown again this R session)
#> Iteration 1 modifying  1 selected rows out of 2: 0 switches, 1 combinations FRFS and 0 combinations LRFS
#> [1] "After minPostCombinationDuration: 1"
#> After minPostCombinationDuration: 1
#> [1] "After combinationWindow: 1"
#> After combinationWindow: 1
#> Time needed to execute combination window 0.00106899738311768

print(result)
#>    person_id index_year event_cohort_id event_start_date event_end_date
#> 1:         1       2020         102+101       2020-05-01     2020-06-01
#>    duration_era
#> 1:      31 days
```

<sup>Created on 2023-02-14 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

# example 2

``` r
library(TreatmentPatterns)
#> Warning: replacing previous import 'data.table::last' by 'dplyr::last' when
#> loading 'TreatmentPatterns'
#> Warning: replacing previous import 'data.table::first' by 'dplyr::first' when
#> loading 'TreatmentPatterns'
#> Warning: replacing previous import 'data.table::between' by 'dplyr::between'
#> when loading 'TreatmentPatterns'
#> Creating a generic function for 'toJSON' from package 'jsonlite' in package 'googleVis'
treatment_history <- tibble::tribble(
  ~event_cohort_id,     ~person_id,   ~event_start_date,  ~event_end_date,
  101,                   1,           "2020-05-01",       "2020-06-01",
  102,                   1,           "2020-06-01",       "2020-07-01"
) %>%
  dplyr::mutate(dplyr::across(dplyr::ends_with("date"), as.Date)) %>% 
  data.table::data.table()

treatment_history[,
                  `:=`(duration_era = difftime(event_end_date, event_start_date, units = "days"),
                       index_year = as.numeric(format(event_start_date, "%Y")))]

result <- TreatmentPatterns:::doCombinationWindow(treatment_history, 
                                                  combinationWindow = 0, 
                                                  minPostCombinationDuration = 0)
#> [1] "After combinationWindow: 2"
#> Currently in a tryCatch or withCallingHandlers block, so unable to add global calling handlers. ParallelLogger will not capture R messages, errors, and warnings, only explicit calls to ParallelLogger. (This message will not be shown again this R session)
#> After combinationWindow: 2
#> Time needed to execute combination window 0.000125384330749512

print(result)
#>    event_cohort_id person_id event_start_date event_end_date duration_era
#> 1:             101         1       2020-05-01     2020-06-01      31 days
#> 2:             102         1       2020-06-01     2020-07-01      30 days
#>    index_year
#> 1:       2020
#> 2:       2020

# I think this person should not be in both 101 and 102+101 on the same day
# my expectation is:
tibble::tribble(
  ~event_cohort_id, ~person_id, ~event_start_date, ~event_end_date,
  "101",            1,          "2020-05-01",      "2020-05-31",
  "102+101",        1,          "2020-06-01",      "2020-06-01",
  "102",            1,          "2020-06-02",      "2020-07-01"
)
#> # A tibble: 3 × 4
#>   event_cohort_id person_id event_start_date event_end_date
#>   <chr>               <dbl> <chr>            <chr>         
#> 1 101                     1 2020-05-01       2020-05-31    
#> 2 102+101                 1 2020-06-01       2020-06-01    
#> 3 102                     1 2020-06-02       2020-07-01
```

<sup>Created on 2023-02-14 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by mvankessel-EMC** [comment]
@AniekMarkus Could you have a look at this?

**Comment by AniekMarkus** [comment]
Example 1: this occurs because the total duration of the era is less than combinationWindow, see below (screenshot from [paper](https://www.sciencedirect.com/science/article/pii/S016926072200462X)).

![Screenshot 2023-02-15 at 16 08 50](https://user-images.githubusercontent.com/60397369/219067119-91fdd558-b4b1-4b5f-a9d2-8a6d9437532e.png)

Example 2: I agree with the expectation, also the combined treatment (101+102) does not seem to be generated at all so that should be corrected too.

**Comment by ablack3** [comment]
@AniekMarkus What should the correct output be in example 1? (Both A and B are the exact same length. That length is greater than `minEraDuration` but less than `combinationWindow`)

**Comment by AniekMarkus** [comment]
@ablack3 The output is correct / should be as was returned:

print(result)
#>    person_id index_year event_cohort_id event_start_date event_end_date
#> 1:         1       2020         102+101       2020-05-01     2020-06-01
#>    duration_era
#> 1:      31 days

Reason is that overlap = event era length (minEraDuration has no influence here). See **bold** part below:
If the overlap of the two event eras is at least combination Window **OR the overlap is
equal to the total length of one of the events**, this is considered:
b. FRFS ('First Received, First Stopped*) if the end date of the earlier starting event era is before or at the end date of the later starting event era.

**Comment by ablack3** [comment]
Ok thanks for explaining @AniekMarkus. Just to check my understanding of the intended output are these examples correct?
<img width="1020" alt="image" src="https://user-images.githubusercontent.com/10227522/219137359-9c4042ac-1dee-4b4f-85bb-8f573b85c80a.png">

<img width="1029" alt="image" src="https://user-images.githubusercontent.com/10227522/219137474-f410bad5-668e-4cb7-b53c-f263a01194fd.png">

It seems that the difference in output between B=A and B=(A+ 1 more day) is significant.

**Comment by ablack3** [comment]
@AniekMarkus One more question I had: Should `doCombinationWindow` guarantee that a person is only ever in one event (possibly a combination event) at any given point in time? 
Seems to me like the answer should be yes, the output of `doCombinationWindow` should not include any overlapping intervals for a single person.

Another way to phrase the question is "Is it possible for a person to be in more than one treatment pathway at the same point in time?" I think the answer here should be no it is not possible.

**Comment by AniekMarkus** [comment]
- The first example is incorrect: if A = B, then full period is converted to A+B no matter what combinationWindow is set to.
- The second example is also incorrect: because A overlaps with B for the entire duration of A, you get similar output as for the third example.
- The third example is correct.

Indeed the resulting pathways should not have any overlapping events, so that would be a good check to perform!

**Comment by ablack3** [comment]
Thanks @AniekMarkus. Are these input/outputs correct?

<img width="1159" alt="image" src="https://user-images.githubusercontent.com/10227522/219714222-b8d6c312-c1d5-43c8-ab85-157153401452.png">

In the above two cases the user's parameters (`combinationWindow`) would be the same but the output is quite different because of a 1 day difference in treatment exposure. What is the reasoning behind this behavior of the algorithm? Why would a 1 day difference in the start date of A determine if A and B should be considered a combination or not?

**Comment by ablack3** [comment]
This is really helpful @AniekMarkus . I'd like to comprehensively test every possible case for doCombinationWindow.
