### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by AniekMarkus** [darwin-eu-dev/TreatmentPatterns#4]
**Is your feature request related to a problem? Please describe.**
Add unit tests to the package.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Basic tests are straightforward, would be good to invest some time in tests for complexer pathways / edge-cases (e.g. different ways of treatment overlap, 3 or more overlapping treatments, behavior of minEraDuration <-> minPostCombinationDuration) .

**Comment by mvankessel-EMC** [comment]
Closing issue as, each function has it's own issue now for testing and documentation
