### ISSUE TITLE
Check function: loadRenderTranslateSql

### ISSUE THREAD

**Issue by mvankessel-EMC** [darwin-eu-dev/TreatmentPatterns#49]
1. Function documentation in order with SRS (Roxygen2)
2. Functionality in order with function documentation
3. Unit test in order with TestPlan (usethis, testthat)
4. Code review of function (other dev than whoever picked up this ticket) (lintr)

**Comment by rossdwilliams** [comment]
@mvankessel-EMC is this not a function that is contained within the sqlRender package from ohdsi? Is it intentionally inside this package?

**Comment by mvankessel-EMC** [comment]
Yes @rossdwilliams , I'll move this issue out for now. There are more functions that I'd like to cut. We can discuss these next Monday.

**Comment by mvankessel-EMC** [comment]
Function is deperecated
