### ISSUE TITLE
Change to arrow?

### ISSUE THREAD

**Issue by AniekMarkus** [darwin-eu-dev/TreatmentPatterns#5]
**Is your feature request related to a problem? Please describe.**
Investigate use of arrow library to improve speed (https://arrow.apache.org/docs/r/).

**Describe the solution you'd like**
Check if this library has potential to speed up the creation of treatment pathways. 

**Describe alternatives you've considered**
Keeping the package as is.

**Additional context**
Promising speed improvements in other HADES packages, e.g. PLP.

**Comment by mvankessel-EMC** [comment]
Arrow could be useful, however in the testing environment it is hard to test how useful it is, as all the csv-files read in by the package are so small that there is no benefit. It performs 5-10x slower on files this small.

I'll take another look at this once I get user feedback, and get a grasp on how big the new aggregated files actually are.

**Comment by mvankessel-EMC** [comment]
See #143, switched implementation to Andromeda in #152.
