### ISSUE TITLE
Allow stratified analysis

### ISSUE THREAD

**Issue by AniekMarkus** [darwin-eu-dev/TreatmentPatterns#6]
**Is your feature request related to a problem? Please describe.**
Allow outputting results for subpopulations without re-running package.

**Describe the solution you'd like**
Allow to add optional column with a 'group_id' (e.g. based on age/ gender / ...) when extracting the treatment history from the database, so that pathways can be aggregated in different ways in the final stage. 

**Describe alternatives you've considered**
Currently need re-running the package when interested in a specific stratification/ subpopulation, which is time-consuming.

**Additional context**

**Comment by mvankessel-EMC** [comment]
Stratification has been added in #152 for age groups, sex, and index year.
